Remove covid19 and YouTube demos
trane-dev/Trane pull request #131
Opened 2023-08-06 01:33 UTC by PatrikDurdevic

2023-08-07 02:46 UTC, PatrikDurdevic commented
Had to remove bz2 dataset compression in the process since pip wasn't packaging it

2023-08-07 02:52 UTC, PatrikDurdevic commented
Also, there is only 1 integration test for airbnb reviews since the store integration test takes too long (3 hours, it's currently commented out for that reason)

2023-08-07 22:16 UTC, gsheni commented on .github/workflows/test_without_dev_deps.yaml
> +              trane.typing.logical_types.Categorical, semantic_tags={"category", "primary_key"}
```suggestion
              ('Categorical', {"category", "primary_key"})
```

2023-08-07 22:16 UTC, gsheni commented on .github/workflows/test_without_dev_deps.yaml
> +              trane.typing.logical_types.Categorical, semantic_tags={"category", "primary_key"}
Optional (trying to make things easier for users)

2023-08-07 22:19 UTC, gsheni commented on trane/datasets/data/store/README.md
> +# Dell Store 2
Add these files to here:
https://github.com/trane-dev/Trane/blob/3f2b256e3acd44c43ab03a7f3cff3e6d4d54893f/pyproject.toml#L81

2023-08-07 22:19 UTC, gsheni commented on trane/datasets/data/store/LICENSE
> +		    GNU GENERAL PUBLIC LICENSE
Add this file to here:
https://github.com/trane-dev/Trane/blob/main/pyproject.toml#L69

2023-08-07 22:21 UTC, gsheni requested changes
Left some minor comments. Overall, looks good.

2023-08-07 22:22 UTC, gsheni commented
> Had to remove bz2 dataset compression in the process since pip wasn't packaging it

This is because the file was not included here:
https://github.com/trane-dev/Trane/blob/main/pyproject.toml#L81

2023-08-07 22:22 UTC, gsheni commented
> Also, there is only 1 integration test for airbnb reviews since the store integration test takes too long (3 hours, it's currently commented out for that reason)

Yep, this is fine. We should try to rely on unit tests as much as possible.

2023-08-10 02:51 UTC, gsheni commented on .github/workflows/test_without_dev_deps.yaml
> +              trane.typing.logical_types.Categorical, semantic_tags={"category", "primary_key"}
Disregard this comment.

2023-08-10 18:24 UTC, gsheni approved these changes

2023-08-10 18:24 UTC, merged